---
apiVersion: v1
kind: Secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQVdHZ0F3SUJBZ0lVWDNIQU15SjVpakVaditFVDNiaDFmU1lzVWs4d0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1WldRZ1kyVnlkREFnRncwM05UQXhNREV3TURBdwpNREJhR0E4ME1EazJNREV3TVRBd01EQXdNRm93SVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1ClpXUWdZMlZ5ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkl3MVFCVlpORjlFUjI5RDlnU2QKZktkZm9EcUxWaUJueThPVHNVSzRmYm12UWZjM21ScERrOXlTUVBjNk42OUhnektNWU9VQUdLVzI1TXBIU2ZDawpYKzJqZFRCek1IRUdBMVVkRVFScU1HaUNLM05oY21WdVlTMXJkV0psY201bGRHVnpMWGRsWW1odmIyc3VjMkZ5ClpXNWhMWE41YzNSbGJTNXpkbU9DT1hOaGNtVnVZUzFyZFdKbGNtNWxkR1Z6TFhkbFltaHZiMnN1YzJGeVpXNWgKTFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBcjM2Wgp2Mk8zcGhNanBQVE02aTRKQWpTcHpIKzVwWGJ5NHdNbkJwZWNYRXdDSVFEUklQWjJBc2VaR2pVMThQaG5lN0xTCkh1bEtoRHdFZkg2SVYxYWlkSTB4b2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZzlvbXNNQW1tUTZOR1VXQTYKNHZFT3dMV3RETXVmWW90MGhvVElGUGNwTkQraFJBTkNBQVNNTlVBVldUUmZSRWR2US9ZRW5YeW5YNkE2aTFZZwpaOHZEazdGQ3VIMjVyMEgzTjVrYVE1UGNra0QzT2pldlI0TXlqR0RsQUJpbHR1VEtSMG53cEYvdAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: sarena-kubernetes-webhook-tls
  namespace: sarena-system
type: kubernetes.io/tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: addresspool.sarena.erwinkok.org
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQVdHZ0F3SUJBZ0lVWDNIQU15SjVpakVaditFVDNiaDFmU1lzVWs4d0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1WldRZ1kyVnlkREFnRncwM05UQXhNREV3TURBdwpNREJhR0E4ME1EazJNREV3TVRBd01EQXdNRm93SVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1ClpXUWdZMlZ5ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkl3MVFCVlpORjlFUjI5RDlnU2QKZktkZm9EcUxWaUJueThPVHNVSzRmYm12UWZjM21ScERrOXlTUVBjNk42OUhnektNWU9VQUdLVzI1TXBIU2ZDawpYKzJqZFRCek1IRUdBMVVkRVFScU1HaUNLM05oY21WdVlTMXJkV0psY201bGRHVnpMWGRsWW1odmIyc3VjMkZ5ClpXNWhMWE41YzNSbGJTNXpkbU9DT1hOaGNtVnVZUzFyZFdKbGNtNWxkR1Z6TFhkbFltaHZiMnN1YzJGeVpXNWgKTFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSkFEQkdBaUVBcjM2Wgp2Mk8zcGhNanBQVE02aTRKQWpTcHpIKzVwWGJ5NHdNbkJwZWNYRXdDSVFEUklQWjJBc2VaR2pVMThQaG5lN0xTCkh1bEtoRHdFZkg2SVYxYWlkSTB4b2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: sarena-kubernetes-webhook
      namespace: sarena-system
      path: /validate/addresspool
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: addresspool.sarena.erwinkok.org
  rules:
  - apiGroups:
    - sarena.erwinkok.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools
    scope: Cluster
  sideEffects: None
  timeoutSeconds: 5
