---
apiVersion: v1
kind: Secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdHZ0F3SUJBZ0lVSjB1T2lTdEFQMHhXbWl5R3duV3BXK0JobFRrd0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1WldRZ1kyVnlkREFnRncwM05UQXhNREV3TURBdwpNREJhR0E4ME1EazJNREV3TVRBd01EQXdNRm93SVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1ClpXUWdZMlZ5ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk4ydGFITUdSOUxrVTVWODdZYm8KZGI2MHpGbzJhNmhUMFM5eHUyeXpoak1wOGtEcndWZmxRNnRBdUFqRnpKSFNmZ20weXNBVTBoMW95ZFNSZGUzdwpJS3FqZFRCek1IRUdBMVVkRVFScU1HaUNLM05oY21WdVlTMXJkV0psY201bGRHVnpMWGRsWW1odmIyc3VjMkZ5ClpXNWhMWE41YzNSbGJTNXpkbU9DT1hOaGNtVnVZUzFyZFdKbGNtNWxkR1Z6TFhkbFltaHZiMnN1YzJGeVpXNWgKTFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBODRxYQpxSXhBR1RaOFlhOUpDN1JLMUYxTURNR2ZQT3FOV2ZuOEVCSFpRblVDSUI0ZUJSWEdvTGVEYnIwZnJIQTgvdk1NCmZFUGlqU2JDMkk2TXVmZkZkbWxqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0tQMktqSHY1ZDFoT1lmZUQKQldWZDRZSEJVV0xvVHRQakNYMWpsNjJRZkQyaFJBTkNBQVRkcldoekJrZlM1Rk9WZk8yRzZIVyt0TXhhTm11bwpVOUV2Y2J0c3M0WXpLZkpBNjhGWDVVT3JRTGdJeGN5UjBuNEp0TXJBRk5JZGFNblVrWFh0OENDcQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: sarena-kubernetes-webhook-tls
  namespace: sarena-system
type: kubernetes.io/tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: addresspool.sarena.erwinkok.org
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdHZ0F3SUJBZ0lVSjB1T2lTdEFQMHhXbWl5R3duV3BXK0JobFRrd0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1WldRZ1kyVnlkREFnRncwM05UQXhNREV3TURBdwpNREJhR0E4ME1EazJNREV3TVRBd01EQXdNRm93SVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1ClpXUWdZMlZ5ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk4ydGFITUdSOUxrVTVWODdZYm8KZGI2MHpGbzJhNmhUMFM5eHUyeXpoak1wOGtEcndWZmxRNnRBdUFqRnpKSFNmZ20weXNBVTBoMW95ZFNSZGUzdwpJS3FqZFRCek1IRUdBMVVkRVFScU1HaUNLM05oY21WdVlTMXJkV0psY201bGRHVnpMWGRsWW1odmIyc3VjMkZ5ClpXNWhMWE41YzNSbGJTNXpkbU9DT1hOaGNtVnVZUzFyZFdKbGNtNWxkR1Z6TFhkbFltaHZiMnN1YzJGeVpXNWgKTFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUVBODRxYQpxSXhBR1RaOFlhOUpDN1JLMUYxTURNR2ZQT3FOV2ZuOEVCSFpRblVDSUI0ZUJSWEdvTGVEYnIwZnJIQTgvdk1NCmZFUGlqU2JDMkk2TXVmZkZkbWxqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: sarena-kubernetes-webhook
      namespace: sarena-system
      path: /validate/addresspool
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: addresspool.sarena.erwinkok.org
  rules:
  - apiGroups:
    - sarena.erwinkok.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools
    scope: Cluster
  sideEffects: None
  timeoutSeconds: 5
