---
apiVersion: v1
kind: Secret
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdHZ0F3SUJBZ0lVY3h5MHphQWgyQlNOam9OSU1kNTlpUXg1QnJvd0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1WldRZ1kyVnlkREFnRncwM05UQXhNREV3TURBdwpNREJhR0E4ME1EazJNREV3TVRBd01EQXdNRm93SVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1ClpXUWdZMlZ5ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk9ScTZ6UEx0THZZUnRQQ0cyNlQKSzFqbXJHNDBsT1VMa1g2bmVJMFV4M2xHUTk4UjBrL2JKZkc4SGlXRGcxbm9nUHRtamRrcVVzR1FFdkNoRTRtMQpxcGVqZFRCek1IRUdBMVVkRVFScU1HaUNLM05oY21WdVlTMXJkV0psY201bGRHVnpMWGRsWW1odmIyc3VjMkZ5ClpXNWhMWE41YzNSbGJTNXpkbU9DT1hOaGNtVnVZUzFyZFdKbGNtNWxkR1Z6TFhkbFltaHZiMnN1YzJGeVpXNWgKTFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFtNnFCTQpjWU9yYkdJd0l0N2F0aHBHZXVCbVJFRm9nc1RzTmZOSGZweEo0Z0loQUlzODVETnBJdVcrVkFtRE50MlNneWtLCnU5UVBjV3UxNU1nSWNjNlUvZnljCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZy8wVlc3TmFIaVZrYmhicmMKTTFGTzhzK3c0QnBqdDRyclBSNnNVTEg0TzJPaFJBTkNBQVRrYXVzenk3UzcyRWJUd2h0dWt5dFk1cXh1TkpUbApDNUYrcDNpTkZNZDVSa1BmRWRKUDJ5WHh2QjRsZzROWjZJRDdabzNaS2xMQmtCTHdvUk9KdGFxWAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
metadata:
  name: sarena-kubernetes-webhook-tls
  namespace: sarena-system
type: kubernetes.io/tls
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: addresspool.sarena.erwinkok.org
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ1ekNDQVdHZ0F3SUJBZ0lVY3h5MHphQWgyQlNOam9OSU1kNTlpUXg1QnJvd0NnWUlLb1pJemowRUF3SXcKSVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1WldRZ1kyVnlkREFnRncwM05UQXhNREV3TURBdwpNREJhR0E4ME1EazJNREV3TVRBd01EQXdNRm93SVRFZk1CMEdBMVVFQXd3V2NtTm5aVzRnYzJWc1ppQnphV2R1ClpXUWdZMlZ5ZERCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQk9ScTZ6UEx0THZZUnRQQ0cyNlQKSzFqbXJHNDBsT1VMa1g2bmVJMFV4M2xHUTk4UjBrL2JKZkc4SGlXRGcxbm9nUHRtamRrcVVzR1FFdkNoRTRtMQpxcGVqZFRCek1IRUdBMVVkRVFScU1HaUNLM05oY21WdVlTMXJkV0psY201bGRHVnpMWGRsWW1odmIyc3VjMkZ5ClpXNWhMWE41YzNSbGJTNXpkbU9DT1hOaGNtVnVZUzFyZFdKbGNtNWxkR1Z6TFhkbFltaHZiMnN1YzJGeVpXNWgKTFhONWMzUmxiUzV6ZG1NdVkyeDFjM1JsY2k1c2IyTmhiREFLQmdncWhrak9QUVFEQWdOSUFEQkZBaUFtNnFCTQpjWU9yYkdJd0l0N2F0aHBHZXVCbVJFRm9nc1RzTmZOSGZweEo0Z0loQUlzODVETnBJdVcrVkFtRE50MlNneWtLCnU5UVBjV3UxNU1nSWNjNlUvZnljCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: sarena-kubernetes-webhook
      namespace: sarena-system
      path: /validate/addresspool
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: addresspool.sarena.erwinkok.org
  rules:
  - apiGroups:
    - sarena.erwinkok.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - addresspools
    scope: Cluster
  sideEffects: None
  timeoutSeconds: 5
