[package]
name = "sarena-services-ipam"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
test-util = []

[dependencies]
sarena-api-types-v1 = { path = "../../sarena-api/types/v1" }

async-trait = { workspace = true }
ipnet = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
