[package]
name = "sarena-services-setup"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
sarena-data-plane = { path = "../../sarena-data-plane" }
sarena-control-plane = { path = "../../sarena-control-plane" }
sarena-infra = { path = "../../sarena-infra" }
sarena-services-daemon = { path = "../../sarena-services/daemon" }
sarena-services-endpoint = { path = "../../sarena-services/endpoint" }
sarena-services-ipam = { path = "../../sarena-services/ipam" }
sarena-shared = { path = "../../sarena-shared" }
sarena-utils = { path = "../../sarena-utils" }

anyhow = { workspace = true }
ipnet = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "signal", "time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
