[package]
name = "sarena-api-server"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
sarena-api-types-v1 = { path = "../../sarena-api/types/v1" }
sarena-infra = { path = "../../sarena-infra" }
sarena-loader = { path = "../../sarena-loader" }
sarena-services-daemon = { path = "../../sarena-services/daemon" }
sarena-services-endpoint = { path = "../../sarena-services/endpoint" }
sarena-services-ipam = { path = "../../sarena-services/ipam" }

anyhow = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
ipnet = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }