[package]
name = "sarena-control-plane"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
test-util = []

[dependencies]
sarena-data-plane = { path = "../sarena-data-plane" }
sarena-infra = { path = "../sarena-infra" }
sarena-shared = { path = "../sarena-shared" }

ipnet = { workspace = true }
thiserror = { workspace = true }
