[package]
name = "sarena-cni-test"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
test = []

[dependencies]
sarena-api-types-v1 = { path = "../../sarena-api/types/v1" }
sarena-cni-plugin = { path = "../../sarena-plugins/cni" }
sarena-infra = { path = "../../sarena-infra", features = ["test"] }
sarena-loader = { path = "../../sarena-loader" }
sarena-shared = { path = "../../sarena-shared" }
sarena-utils = { path = "../../sarena-utils" }

aya = { workspace = true }
axum = { workspace = true }
ipnet = { workspace = true }
rscni-plugin = { workspace = true, features = ["async"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tracing = { workspace = true }
