[package]
name = "sarena-kubernetes"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
axum = { workspace = true }
axum-server = { workspace = true }
futures = { workspace = true }
ipnet = { workspace = true }
kube = { workspace = true, features = ["admission"] }
k8s-openapi = { workspace = true }
prometheus = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[[bin]]
name = "sarena-crdgen"
path = "src/bin/crdgen.rs"

[[bin]]
name = "sarena-certgen"
path = "src/bin/certgen.rs"
