[package]
name = "sarena-kubernetes"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
kube = { workspace = true }
k8s-openapi = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-util = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[[bin]]
name = "sarena-crdgen"
path = "src/bin/crdgen.rs"
