[package]
name = "sarena-daemon"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
sarena-api-server = { path = "../sarena-api/server" }
sarena-control-plane = { path = "../sarena-control-plane" }
sarena-utils = { path = "../sarena-utils" }

anyhow = { workspace = true }
ipnet = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tracing = { workspace = true }

[[bin]]
name = "sarena-daemon"
path = "src/main.rs"
