[package]
name = "sarena-daemon"

edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
sarena-shared = { path = "../sarena-shared", features = ["std"] }
sarena-infra = { path = "../sarena-infra", features = ["test"] }
sarena-loader = { path = "../sarena-loader" }
sarena-utils = { path = "../sarena-utils" }

anyhow = { workspace = true, default-features = true }
aya = { workspace = true }
aya-log = { workspace = true }
hex = { workspace = true, features = ["std"] }
ipnetwork = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
sha2 = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "fmt", "ansi"] }
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "rt-multi-thread",
    "net",
    "signal",
] }
clap = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[[bin]]
name = "sarena-daemon"
path = "src/main.rs"
